# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# master branch only
trigger:
- master

jobs:
- job: Linux

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - script: dotnet test src --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'

- job: macOS

  pool:
    vmImage: 'xcode9-macos10.13'

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - script: dotnet test src --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'
 
- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - script: dotnet test src --configuration $(buildConfiguration)
    displayName: 'dotnet test $(buildConfiguration)'
